/*
	Hoang Cao
	Part two - Midterm

*/


IF OBJECT_ID('Midterm') IS NOT NULL
DROP TABLE Midterm;

IF OBJECT_ID('HCAO_NATIONALPARK') IS NOT NULL
DROP TABLE HCAO_NATIONALPARK;

IF OBJECT_ID('HCAO_CAMPGROUND') IS NOT NULL
DROP TABLE HCAO_CAMPGROUND;

IF OBJECT_ID('HCAO_CAMPSPOT') IS NOT NULL
DROP TABLE HCAO_CAMPSPOT;

IF OBJECT_ID('HCAO_SUPPORT') IS NOT NULL
DROP TABLE HCAO_SUPPORT;

IF OBJECT_ID('HCAO_CONTACT') IS NOT NULL
DROP TABLE HCAO_CONTACT;

IF OBJECT_ID('HCAOMidtermInsert') IS NOT NULL
DROP PROCEDURE HCAOMidtermInsert;

IF OBJECT_ID('HCAOMidtermInsertTrigger') IS NOT NULL
DROP TRIGGER HCAOMidtermInsertTriggert;

IF OBJECT_ID('HCAOMidtermUpdateTrigger') IS NOT NULL
DROP TRIGGER HCAOMidtermUpdateTrigger;

IF OBJECT_ID('HCAOMidtermInsert1') IS NOT NULL
DROP PROCEDURE HCAOMidtermInsert1;
GO
CREATE TABLE Midterm
(
	MidtermKey int IDENTITY (1,1) NOT NULL,
	SomeCharacterValue varchar(255) NULL,
	SomeNumber int NULL,
	DateUpdated smalldatetime NULL
)

GO

/* 
Question #6 - 10 points
*/


CREATE PROCEDURE HCAOMidtermInsert
@NameOfGame NVARCHAR(50) = NULL,   
@Year Int = NULL 
AS
INSERT INTO Midterm (SomeCharacterValue,SomeNumber)
VALUES(@NameOfGame,@Year)
GO
EXECUTE HCAOMidtermInsert @NameOfGame = 'Zelda', @Year = '2017' 
EXECUTE HCAOMidtermInsert @NameOfGame = 'Link'
EXECUTE HCAOMidtermInsert @Year = '2020'
SELECT * FROM Midterm;
GO

/*
Question #7 - 10 points
*/


CREATE PROCEDURE HCAOMidtermInsert1
@KEY INT,
@RulesOfGame NVARCHAR(50) = NULL,   
@Year1 Int = NULL 
AS

UPDATE Midterm 
SET Midterm.SomeCharacterValue = @RulesOfGame, Midterm.SomeNumber = @Year1
WHERE Midterm.MidtermKey = @KEY

GO
EXECUTE HCAOMidtermInsert1 @KEY = 1,@RulesOfGame = 'Zelda Rules', @Year1 = '2017' 
EXECUTE HCAOMidtermInsert1 @KEY = 2,@RulesOfGame = 'ROBIN RULES', @Year1= '2015'

SELECT * FROM Midterm
GO


/*
Question #8 - 15 points
*/
SET IDENTITY_INSERT Midterm ON
GO
CREATE TRIGGER HCAOMidtermInsertTrigger ON Midterm
FOR INSERT
AS
DECLARE @Midtermkey INT
DECLARE @SomeCharacterValue NVARCHAR(50)    
DECLARE @SomeNumber Int 


SELECT @Midtermkey = A.MidtermKey FROM Midterm A
SELECT @SomeCharacterValue = A.SomeCharacterValue FROM Midterm A
SELECT @SomeNumber = A.SomeNumber FROM Midterm A

UPDATE Midterm 
SET MidterM.DateUpdated= GETDATE()
WHERE @SomeCharacterValue  = Midterm.SomeCharacterValue
OR @SomeNumber = Midterm.SomeNumber
OR @Midtermkey = Midterm.MidtermKey
GO
INSERT INTO Midterm (MidtermKey,SomeCharacterValue,SomeNumber)
VALUES(4,'batman',3)
SELECT * FROM Midterm
GO


CREATE TRIGGER HCAOMidtermUpdateTrigger ON Midterm
FOR UPDATE
AS
UPDATE Midterm 
SET Midterm.DateUpdated= GETDATE()
FROM MIDTERM A
INNER JOIN inserted I ON A.SomeCharacterValue = I.SomeCharacterValue
OR A.SomeNumber= I.SomeNumber
GO

UPDATE Midterm 
SET SomeCharacterValue = 'ROBIN'
WHERE SomeNumber = 2017
SELECT * FROM Midterm

SET IDENTITY_INSERT Midterm OFF
GO



/*
Question #9 - 25 points
*/
CREATE TABLE HCAO_NATIONALPARK
(NATIONALPARK_ID INT IDENTITY(1,1) NOT NULL,
NATIONALPARK_NAME NVARCHAR(50) NULL,
NATIONALPARK_CONTACTID INT NULL)

CREATE TABLE HCAO_CAMPGROUND
(CAMPGROUND_ID INT IDENTITY(1,1) NOT NULL,
NATIONALPARK_ID INT NULL,
CAMPSPOT_ID INT NULL)

CREATE TABLE HCAO_CAMPSPOT
(CAMPSPOT_ID INT IDENTITY(1,1) NOT NULL,
CAMPGROUND_ID INT NULL,
SUPPORT_ID INT NULL)

CREATE TABLE HCAO_SUPPORT
(SUPPORT_ID INT IDENTITY(1,1) NOT NULL,
SUPPORT_FOOD NVARCHAR(50) NULL,
SUPPORT_WATER NVARCHAR(50) NULL,
SUPPORT_TENT NVARCHAR(50) NULL)

CREATE TABLE HCAO_CONTACT
(NATIONALPARK_CONTACTID INT NOT NULL,
FIRSTNAME NVARCHAR(50) NULL,
LASTNAME NVARCHAR(50) NULL,
EMAIL NVARCHAR(250) NULL,
PHONE NVARCHAR (250))

ALTER TABLE HCAO_NATIONALPARK
	ADD Constraint PK_HCAO_NATIONALPARK
	PRIMARY KEY CLUSTERED (NATIONALPARK_ID);

ALTER TABLE HCAO_CAMPGROUND
	ADD Constraint PK_CAMPGROUND_ID
	PRIMARY KEY CLUSTERED(CAMPGROUND_ID);
	
ALTER TABLE HCAO_CAMPSPOT
	ADD Constraint PK_HCAO_CAMPSPOT
	PRIMARY KEY CLUSTERED (CAMPSPOT_ID);

ALTER TABLE HCAO_SUPPORT
	ADD Constraint PK_HCAO_SUPPORT
	PRIMARY KEY CLUSTERED (SUPPORT_ID);

ALTER TABLE HCAO_CONTACT
	ADD Constraint PK_HCAO_CONTACT
	PRIMARY KEY CLUSTERED (NATIONALPARK_CONTACTID);

ALTER TABLE HCAO_NATIONALPARK
	ADD Constraint FK_HCAO_NATIONALPARK
	FOREIGN KEY (NATIONALPARK_CONTACTID)REFERENCES HCAO_CONTACT(NATIONALPARK_CONTACTID)
		

ALTER TABLE HCAO_CAMPGROUND
	ADD Constraint FK1_HCAO_CAMPGROUND
	FOREIGN KEY (CAMPSPOT_ID)REFERENCES HCAO_CAMPSPOT(CAMPSPOT_ID)
ALTER TABLE HCAO_CAMPGROUND
	ADD Constraint FK2_HCAO_CAMPGROUND
	FOREIGN KEY (NATIONALPARK_ID)REFERENCES HCAO_NATIONALPARK(NATIONALPARK_ID);
	
ALTER TABLE HCAO_CAMPSPOT
	ADD Constraint FK_HCAO_CAMPSPOT
	FOREIGN KEY (SUPPORT_ID)REFERENCES HCAO_SUPPORT(SUPPORT_ID);

ALTER TABLE HCAO_NATIONALPARK
DROP CONSTRAINT FK_HCAO_NATIONALPARK

ALTER TABLE HCAO_CAMPGROUND
DROP CONSTRAINT FK1_HCAO_CAMPGROUND

ALTER TABLE HCAO_CAMPGROUND
DROP CONSTRAINT FK2_HCAO_CAMPGROUND

ALTER TABLE HCAO_CAMPSPOT
DROP CONSTRAINT FK_HCAO_CAMPSPOT	
GO